linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/transcom/mymove

linters:
  enable:
     - gosec
     - golint
     - gofmt
     - goimports
     - govet
     - varcheck
     - typecheck
     - structcheck
  disable:
    - unused #deprecated https://github.com/dominikh/go-tools/tree/master/cmd/unused
    - deadcode
    - errcheck #requires patching code
    - gosimple
    - ineffassign
    - staticcheck
issues:
  exclude-rules:
    # skip analyzing dutystationsloader until repeated tags from embedded types are fixed https://github.com/golang/go/issues/30846
    - path: internal/pkg/dutystationsloader/duty_stations_loader.go
      linters:
        - govet