# This file is used only by soda, as that tool does not accept database connection information
# in any other way. It is used in both development AND test environments.
development:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}
